primerproyectodj/urls.py
from django.conf.urls import patterns,include, url #include para la pagina admin
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
	url(r'^preguntas/$','preguntasyrespuestas.views.index', name='preguntas'),
	url(r'^preguntas/(?P<pregunta_id>\d+)/$','preguntasyrespuestas.views.pregunta_detalle',name='pregunta_detalle'),#cuidar que P es mayuscula
    url(r'^admin/doc/', include('django.contrib.admindocs.urls')),#esta url para el admin
    url(r'^admin/',include(admin.site.urls)),#solo es un extra
    url(r'^preguntas/crear/$','preguntasyrespuestas.views.pregunta_crear',name='pregunta_crear'),
    url(r'^preguntas/editar/(?P<pregunta_id>\d+)/$','preguntasyrespuestas.views.pregunta_editar', name='pregunta_editar'),
    url(r'^login/$','primerproyectodj.views.login_page',name="login"),
    url(r'^$','primerproyectodj.views.homepage',name="homepage"),
    url(r'^logout/$','primerproyectodj.views.logout_view',name="logout"),

















)

preguntasyrespuestas/models.py
from django.db import models
from django.utils import timezone

# Create your models here.
class  Pregunta(models.Model):
	asunto = models.CharField(max_length=200)
	descripcion = models.TextField()
	fecha_publicacion = models.DateTimeField(auto_now_add=True)

	def __str__(self):
		return self.asunto

	def publicado_hoy(self):
		return self.fecha_publicacion.date() == timezone.now().date()
	publicado_hoy.boolean = True
	publicado_hoy.descripcion_corta = 'Preguntado hoy?'


class Respuesta(models.Model):
	Pregunta = models.ForeignKey(Pregunta)
	contenido = models.TextField()
	mejor_respuesta = models.BooleanField("Respuesta preferida",default=False)

	def __str__(self):
		return self.contenido

primerproyectodj/forms.py
from django import forms

class LoginForm(forms.Form):
    username = forms.CharField()
    password = forms.CharField(widget = forms.PasswordInput())

preguntasyrespuestas/views.py
from django.http import HttpResponse
from django.shortcuts import get_object_or_404, render_to_response, redirect
from preguntasyrespuestas.models import Pregunta
from django.template import RequestContext #desde aqui para trabajar con formularios
from preguntasyrespuestas.form import PreguntaForm
from django.contrib.auth.decorators import login_required
from django.utils import timezone

def index(request):
    preguntas = Pregunta.objects.all()
    return render_to_response('preguntasyrespuestas/index.html',{'preguntas':preguntas})


# def pregunta_detalle(request, pregunta_id):
#     try:
#         pregunta = Pregunta.objects.get(pk=pregunta_id)
#     except Pregunta.DoesNotExist:
#         raise Http404
#     return HttpResponse("%s?" % pregunta.asunto)
#
def pregunta_detalle(request, pregunta_id):
    pregunta = get_object_or_404(Pregunta, pk=pregunta_id)
    return render_to_response('preguntasyrespuestas/pregunta_detalle.html',{'pregunta': pregunta})


@login_required
def pregunta_crear(request):
    if request.method == 'POST': #desde aca va para la persistencia de datos
        form = PreguntaForm(request.POST)
        if form.is_valid():
            form.save()
            #CODIGO SUSTITUIDO POR MODELFORM, YA NO ES NECESARIA ESTA INFORMACION MODELFORM YA SE ENCARGA DE ESTO
            # pregunta = Pregunta(asunto=form.cleaned_data['asunto'],
            #                     descripcion=form.cleaned_data['descripcion'],
            #                     fecha_publicacion=timezone.now())
            # pregunta.save()
            return redirect('preguntas')
    else:
        form = PreguntaForm()
    return render_to_response('preguntasyrespuestas/pregunta_crear.html',
                                {'form': form},
                                context_instance=RequestContext(request))


@login_required
def pregunta_editar(request, pregunta_id):
    pregunta = get_object_or_404(Pregunta, pk=pregunta_id)
    if request.method == 'POST':
        form = PreguntaForm(request.POST,instance=pregunta)
        if form.is_valid():
            form.save()
            return redirect('pregunta_detalle',pregunta_id)
    else:
        form = PreguntaForm(instance=pregunta)
    return render_to_response('preguntasyrespuestas/pregunta_editar.html',{'form':form},
                                  context_instance = RequestContext(request))
#[template_directory]/preguntasyrespuestas/index.html -> path a los templates del proyecto

primerproyectodj/views.py
from django.template import RequestContext
from django.shortcuts import render_to_response, redirect
from primerproyectodj.forms import LoginForm
from django.contrib.auth import authenticate, login, logout


def login_page(request):
    message = None
    if request.method == "POST":
        form = LoginForm(request.POST)
        if form.is_valid():
            username = request.POST['username']
            password = request.POST['password']
            user = authenticate(username=username,password=password)
            if user is not None:
                if user.is_active:
                    login(request,user)
                    message = "Bienvenido !"
                else:
                    message = "Tu usario esta inactivo"
            else:
                message = "Nombre de usuario y/o password incorrecto"
    else:
        form = LoginForm()
    return render_to_response('login.html',{'message':message,'form':form},context_instance=RequestContext(request))


def homepage(request):
    return render_to_response('homepage.html',context_instance=RequestContext(request))

def logout_view(request):
    logout(request)
    return redirect('homepage')

templates/base.html
<!DOCTYPE html>
<html lang="es">
<head>
    <title>Proyecto en Django, Hola mundo! | {% block title %} Inicio {% endblock %}</title>
</head>
<body>
        <div id="header">
            {% if user.is_authenticated %}
            <p>Bienvenido, <b>{{ user.username }} | <a href="{% url "logout" %}">Logout</a> </b></p>
            {% else %}
                <p>Bienvenido, Por favor <a href="{% url "login" %}">log in</a> </p>
            {% endif %}
            <h1>Curso de Django.</h1>
        </div>
        <div id="content">
            {% block content %}{% endblock %}
        </div>
    <div id="navigation">
        <p><a href="{% url "homepage" %}">Inicio</a> | <a href="{% url "preguntas" %}">Preguntas</a> </p>
    </div>
</body>
</html>

templates/base2.html
<!DOCTYPE html>
<html lang="es">
<head>
    <title>Proyecto en Django, Hola mundo! | {% block title %} Inicio {% endblock %}</title>
</head>
<body>
        <div id="header">
            <h1>Curso de Django.</h1>
        </div>
        <div id="content">
            {% block content %}{% endblock %}
        </div>
    <div id="navigation">
        <p><a href="{% url "homepage" %}">Inicio</a> | <a href="{% url "preguntas" %}">Preguntas</a> </p>
    </div>
</body>
</html>

templates/homepage.html
{% extends "base.html" %}
{% block title %} Bienvenido! {% endblock %}
{% block content %}
    <h3>Bienvenido, esta es nuestra pagina de inicio</h3>
{% endblock %}

templates/login.html
{% extends "base.html" %}
{% block title %} Login {% endblock %}
{% block content %}
    <h1>Login</h1>
    {% if message %}
    <b>{{ message }}</b>
    {% endif %}
    <form action="" method="post">{% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Submit" />
    </form>
{% endblock %}

templates/preguntasyrespuestas/form_snippets.html
 {% for field in form %}
            <div class="field_container">
                {{ field.errors }} {#Mostrara error si es que hay uno#}
                {{ field.label_tag }} </br>{# Mostrara el nombre del campo#}
                {{ field }}{# Mostrara el contenido del campo#}
            </div>
 {% endfor %}

templates/preguntasyrespuestas/index.html
{% extends "base2.html" %}
{% block title %} Preguntas {% endblock %}
{% block content %}
    <p><a href="{% url "pregunta_crear" %}">Crear una pregunta</a> </p>
    {% for pregunta in preguntas %}
        <a href="{% url "pregunta_detalle" pregunta.id %}">{{ pregunta.asunto }} ?</a></br>
{% endfor %}
{% endblock %}

templates/preguntasyrespuestas/pregunta_crear.html
{% extends "base.html" %}<!-- hereda de la plantilla base la cabecera -->
{% block title %}Crear una pregunta{% endblock %}
{% block content %}
    <form action="" method="post"> {% csrf_token %}
{#    {{ form.as_p }}<!-- renderiza el formulario por parrafos -->#}
        {% include "preguntasyrespuestas/form_snippets.html" %}
        <input type="submit" value="Submit">
    </form>
{% endblock %}

templates/preguntasyrespuestas/pregunta_detalle.html
{% extends "base.html" %}
{% block title %} Pregunta detalle {% endblock %}
{% block content %}
    <h2>{{ pregunta.asunto }}?</h2>
    <p><a href="{% url "pregunta_editar" pregunta.id %}">Editar esta pregunta</a> </p> <!-- enlace a editar-->
    <p><b>Publicado:</b>{{ pregunta.fecha_publicacion|date:"D, d/m/Y" }}</p>
    <p>
        {% if pregunta.descripcion %}
        {{ pregunta.descripcion }}
        {% else %}
            No se ha incluido descripcion
        {% endif %}
    </p>
    <h3>Respuestas</h3>
    <ul>
        {% for respuesta in pregunta.respuesta_set.all %}
            <li>{{ respuesta.contenido|safe }}</li>
        {% empty %}
            <li>Aun no hay respuestas</li>
        {% endfor %}
    </ul>
{% endblock %}

templates/preguntasyrespuestas/pregunta_detalle2.html
{% extends "base.html" %}
{% block title %} Pregunta detalle {% endblock %}
{% block content %}
    <h2>{{ pregunta.asunto }}?</h2>
    <p><b>Publicado:</b>{{ pregunta.fecha_publicacion | date: "D, d/m/Y" }}</p>
    <p>
        {% if pregunta.descripcion %}
        {{ pregunta.descripcion }}
        {% else %}
            No se ha incluido descripcion
        {% endif %}
    </p>
    <h3>Respuestas</h3>
    <ul>
        {% for respuesta in pregunta.respuesta_set.all %}
            <li>{{ respuesta.contenido|safe }}</li>
        {% empty %}
            <li>Aun no hay respuestas</li>
        {% endfor %}
    </ul>
{% endblock %}

<!DOCTYPE html>
<html>
<head>
    <title>Detalle Pregunta</title>
</head>
<body>
    <h2>{{pregunta.asunto}}?</h2>
    <p><b>Publicado:</b>{{pregunta.fecha_publicacion|date:"D, d/m/Y"}}</p>
    <p>{% if pregunta.descripcion %}
        {{pregunta.descripcion}}
        {% else %}
        No se ha incluido descripcion.
        {% endif %}
    </p>
    <h3>Respuestas</h3>
    <ul>
        {% for respuesta in pregunta.respuesta_set.all %}
        <li>{{respuesta.contenido|safe}}</li>
        {% empty %}
        <li>Aun no hay respuestas</li>
        {% endfor %}
    </ul>
</body>
</html>

templates/preguntasyrespuestas/pregunta_editar.html
{% extends "base.html" %}<!-- hereda de la plantilla base la cabecera -->
{% block title %}Editar una pregunta{% endblock %}
{% block content %}
    <form action="" method="post"> {% csrf_token %}
{#    {{ form.as_p }} <!--renderiza el formulario por parrafos --> REEMPLAZADO PARA DAR ESTILO AL FORM#}
       {% include "preguntasyrespuestas/form_snippets.html" %}
        <input type="submit" value="Submit">
    </form>
{% endblock %}